# Generated by Django 4.0 on 2022-01-10 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_profile_usertostep_usertomodule_usertolesson_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='about_me_text',
            field=models.TextField(blank=True),
        ),
    ]
