# Generated by Django 4.0 on 2022-01-10 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_profile_about_me_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='about_me_text',
            field=models.TextField(blank=True, default=''),
        ),
    ]
