# Generated by Django 4.0 on 2022-01-26 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_profile_last_name_remove_profile_mail_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_description', models.TextField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.course')),
            ],
        ),
        migrations.CreateModel(
            name='CourseStars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('five_stars_count', models.IntegerField()),
                ('four_stars_count', models.IntegerField()),
                ('three_stars_count', models.IntegerField()),
                ('two_stars_count', models.IntegerField()),
                ('one_stars_count', models.IntegerField()),
                ('course_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.courseinfo')),
            ],
        ),
        migrations.CreateModel(
            name='CourseSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('course_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.courseinfo')),
            ],
        ),
        migrations.CreateModel(
            name='CourseFit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('course_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.courseinfo')),
            ],
        ),
        migrations.CreateModel(
            name='CourseComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.TextField()),
                ('stars_count', models.IntegerField()),
                ('course_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.courseinfo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.profile')),
            ],
        ),
    ]
