# Generated by Django 4.0 on 2022-01-26 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_profile_avatar_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='avatar_url',
        ),
    ]
