# Generated by Django 4.0 on 2022-01-26 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_coursefit_title_alter_courseskill_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursestars',
            name='five_stars_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='coursestars',
            name='four_stars_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='coursestars',
            name='one_stars_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='coursestars',
            name='three_stars_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='coursestars',
            name='two_stars_count',
            field=models.IntegerField(default=0),
        ),
    ]
