# Generated by Django 4.0 on 2022-01-28 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_coursestars_five_stars_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='url',
            field=models.SlugField(default=models.CharField(max_length=100)),
        ),
    ]
