# Generated by Django 4.0 on 2022-01-28 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_course_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='url',
            field=models.SlugField(),
        ),
    ]
