# Generated by Django 4.0 on 2022-01-28 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_course_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='url',
            new_name='slug',
        ),
    ]
