# Generated by Django 4.0 on 2022-01-28 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_rename_url_course_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='slug',
        ),
    ]
