# Generated by Django 4.0 on 2022-01-10 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0007_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
