# Generated by Django 4.0 on 2022-01-26 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0009_courseinfo_coursestars_courseskill_coursefit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='author_id',
        ),
        migrations.RemoveField(
            model_name='coursecomment',
            name='course_info_id',
        ),
        migrations.RemoveField(
            model_name='coursecomment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='coursefit',
            name='course_info_id',
        ),
        migrations.RemoveField(
            model_name='courseinfo',
            name='course_id',
        ),
        migrations.RemoveField(
            model_name='courseskill',
            name='course_info_id',
        ),
        migrations.RemoveField(
            model_name='coursestars',
            name='course_info_id',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='module_id',
        ),
        migrations.RemoveField(
            model_name='module',
            name='course_id',
        ),
        migrations.RemoveField(
            model_name='step',
            name='lesson_id',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='CourseComment',
        ),
        migrations.DeleteModel(
            name='CourseFit',
        ),
        migrations.DeleteModel(
            name='CourseInfo',
        ),
        migrations.DeleteModel(
            name='CourseSkill',
        ),
        migrations.DeleteModel(
            name='CourseStars',
        ),
        migrations.DeleteModel(
            name='Lesson',
        ),
        migrations.DeleteModel(
            name='Module',
        ),
        migrations.DeleteModel(
            name='Step',
        ),
    ]
