# Generated by Django 4.0 on 2022-01-26 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0011_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='author_id',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='lesson',
            old_name='module_id',
            new_name='module',
        ),
        migrations.RenameField(
            model_name='module',
            old_name='course_id',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='step',
            old_name='lesson_id',
            new_name='lesson',
        ),
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
