# Generated by Django 4.0 on 2022-01-26 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0013_rename_course_info_id_coursecomment_course_info_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursecomment',
            old_name='course_info',
            new_name='course_info_id',
        ),
        migrations.RenameField(
            model_name='coursefit',
            old_name='course_info',
            new_name='course_info_id',
        ),
        migrations.RenameField(
            model_name='courseinfo',
            old_name='course',
            new_name='course_id',
        ),
        migrations.RenameField(
            model_name='courseskill',
            old_name='course_info',
            new_name='course_info_id',
        ),
        migrations.RenameField(
            model_name='coursestars',
            old_name='course_info',
            new_name='course_info_id',
        ),
    ]
