# Generated by Django 4.0 on 2022-01-26 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0014_rename_course_info_coursecomment_course_info_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CourseComment',
        ),
    ]
