# Generated by Django 4.0 on 2022-01-26 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('frontend', '0015_delete_coursecomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.DateTimeField(auto_created=True)),
                ('comment', models.TextField()),
                ('stars_count', models.IntegerField()),
                ('course_info_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.courseinfo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
    ]
