# Generated by Django 4.0 on 2022-01-26 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0016_coursecomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursecomment',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
